(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'bs-13',
          componentName:'CookieBanner',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:""
        });
      })({"bannerTitle":"Политика использования файлов cookie","acceptText":"Принять и закрыть","declineEnabled":null,"declineText":"Decline","message":"{\"blocks\":[{\"key\":\"688aj\",\"text\":\"Этот сайт использует куки. Продолжая использовать этот сайт, вы соглашаетесь с использованием нами файлов cookie.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}","preset":"footer4","staticContent":{"YouTube":"YouTube Social Link","Facebook":"Facebook Social Link","acceptAndClose":"Accept & Close","Xing":"Xing Social Link","Houzz":"Houzz Social Link","Yelp":"Yelp Social Link","usingCookieTitle":"This website is using cookies.","Google+":"Google Plus Social Link","Instagram":"Instagram Social Link","Twitter":"Twitter Social Link","cookiePolicy":"Cookie Policy","decline":"Decline","Pinterest":"Pinterest Social Link","LinkedIn":"LinkedIn Social Link","usingCookieMessage":"We use them to give you the best experience. If you continue using our website, we'll assume that you are happy to receive all cookies on this website."},"pages":[],"copyright":"{\"blocks\":[{\"key\":\"bii86\",\"text\":\"Copyright © 2020 PinupArt Gallery - Все права защищены.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{\"fontScale\":0}}],\"entityMap\":{}}","poweredBy":"Powered by GoDaddy Website Builder","isAccountFree":false,"appName":"Website Builder","cookieBannerEnabled":true,"cookieBannerMessage":"{\"blocks\":[{\"key\":\"688aj\",\"text\":\"Этот сайт использует куки. Продолжая использовать этот сайт, вы соглашаетесь с использованием нами файлов cookie.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}","cookieBannerTitle":"Политика использования файлов cookie","cookieBannerButtonLabel":"Принять и закрыть","cookieBannerDeclineEnabled":null,"cookieBannerDeclineLabel":"Decline","isReseller":false,"market":"en-US","rootDomain":"godaddy.com","planUpgradeLink":"https:\u002F\u002Fwww.godaddy.com\u002Fwebsites\u002Fwebsite-builder?isc=ISC#pricing","socialAccountsEnabled":false,"facebookProfile":null,"twitterProfile":null,"instagramProfile":null,"pinterestProfile":null,"linkedinProfile":null,"youtubeProfile":null,"yelpProfile":null,"houzzProfile":null,"xingProfile":null,"businessName":"PinupArt Gallery","address":"Moldova-Sulița, Suceava, Romania","phone":null,"id":"banner-b6879de9-8de4-4a09-b416-101f3b468849","widgetId":"b6879de9-8de4-4a09-b416-101f3b468849","section":"default","category":"neutral","locale":"en-US","renderMode":"PUBLISH"},{"widgetId":"b6879de9-8de4-4a09-b416-101f3b468849","widgetType":"FOOTER","widgetPreset":"footer4","order":5,"section":"default","category":"neutral","fontSize":"medium","fontFamily":"alternate","group":"Section","groupType":"Default"});