(function(props,context) {
        Core.utils.renderBootstrap({
          elId:'97a18e93-245c-41fb-a46b-a6f7ddd3798c-bootstrap-container',
          componentName:'ContactForm1',
          props:props,
          context:context,
          contextKey:'context-bs-1',
          radpack:""
        });
      })({"formTitle":"Оставьте нам сообщение!","formFields":[{"type":"SINGLE_LINE","label":"Name","required":false},{"type":"EMAIL","label":"Email","validation":"email","required":true,"replyTo":true},{"type":"MULTI_LINE","label":"Message","required":false},{"type":"SUBMIT","label":"Отправить","required":false}],"blankInfo":false,"formSubmitHost":"https:\u002F\u002Fcontact.apps-api.instantpage.secureserver.net","showMap":false,"recaptchaEnabled":true,"recaptchaType":"V3","domainName":"stroyinvest.godaddysites.com","formSuccessMessage":"{\"blocks\":[{\"key\":\"ckd7p\",\"text\":\"Thank you for your inquiry! We will get back to you within 48 hours.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}","formEnabled":true,"websiteId":"c30a9110-c36c-4075-89e2-860a734bda68","pageId":"eb58e47a-478e-4162-b307-c83b9b36d53b","accountId":"6b6fbab8-72eb-11ea-81c6-3417ebe725c2","staticContent":{"today":"Today","submitButtonLoadingLabel":"Sending","contactFormResponseErrorMessage":"Something went wrong while sending your message, please try again later","defaultCancelButtonLabel":"Cancel","byAppointment":"By Appointment","defaultSubmitButtonLabel":"Send","closed":"Closed","termsOfSerivce":"Terms of Service","recaptchaDisclosure":"This site is protected by reCAPTCHA and the Google {privacyPolicy} and {termsOfSerivce} apply.","emailValidationErrorMessage":"Please enter a valid email address.","mapCTA":"Get directions","privacyPolicyURL":"https:\u002F\u002Fpolicies.google.com\u002Fprivacy","requiredValidationErrorMessage":"Please fill in this required field","openToday":"Open today","privacyPolicy":"Privacy Policy","termsOfSerivceURL":"https:\u002F\u002Fpolicies.google.com\u002Fterms"},"emailOptInEnabled":false,"emailOptInHidden":false,"emailOptInMessage":"Sign up for our email list for updates, promotions, and more.","emailConfirmationMessage":"We've sent you a confirmation email, please click the link to verify your address.","widgetId":"97a18e93-245c-41fb-a46b-a6f7ddd3798c","section":"default","category":"neutral","locale":"en-US","renderMode":"PUBLISH"},{"widgetId":"97a18e93-245c-41fb-a46b-a6f7ddd3798c","widgetType":"CONTACT","widgetPreset":"contact7","order":4,"section":"default","category":"neutral","fontSize":"medium","fontFamily":"alternate","group":"Content","groupType":"Default"});